import React, { useMemo, useState } from 'react';
import { CalendarPlus, CheckCircle2, ClipboardList, CreditCard, MessageSquare, Send, Settings, UserRound } from 'lucide-react';
import { usePortalData } from '../../data/PortalStore';
import './SchoolWorkflows.css';

export function StaffCalendar() {
  const { academicCalendar, publishAcademicDate } = usePortalData();
  const [entry, setEntry] = useState({ title: '', start: '', end: '', type: 'Resumption' }); const [notice, setNotice] = useState('');
  const submit = (e) => { e.preventDefault(); if (!entry.title || !entry.start) return; publishAcademicDate(entry); setEntry({ title: '', start: '', end: '', type: 'Resumption' }); setNotice('Academic calendar date published to parent and student portals.'); };
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Academic calendar</h1><p className="page-header__subtitle">Only staff publish resumption, vacation, assessment and school-event dates. Families receive the same approved calendar.</p></div><div className="workflow-grid"><section className="panel"><div className="panel__header"><h2 className="panel__title">Published academic dates</h2></div><CalendarList items={academicCalendar}/></section><form className="panel workflow-form" onSubmit={submit}><div className="panel__header"><h2 className="panel__title"><CalendarPlus size={16}/> Publish a date</h2></div><div className="panel__body"><label>Title<input value={entry.title} onChange={(e) => setEntry({ ...entry, title: e.target.value })} required placeholder="e.g. Term 2 resumes"/></label><label>Type<select value={entry.type} onChange={(e) => setEntry({ ...entry, type: e.target.value })}><option>Resumption</option><option>Vacation</option><option>Assessment</option><option>School event</option></select></label><label>Start date<input type="date" value={entry.start} onChange={(e) => setEntry({ ...entry, start: e.target.value })} required/></label><label>End date (optional)<input type="date" value={entry.end} onChange={(e) => setEntry({ ...entry, end: e.target.value })}/></label><button className="workflow-button" type="submit"><CalendarPlus size={15}/> Publish to families</button>{notice && <p className="workflow-success"><CheckCircle2 size={15}/>{notice}</p>}</div></form></div></div>;
}

export function StaffAssignments() {
  const { assignments, publishAssignment } = usePortalData(); const [item, setItem] = useState({ title: '', instructions: '', audience: 'SH2 Class Group', due: '' }); const [notice, setNotice] = useState('');
  const submit = (e) => { e.preventDefault(); if (!item.title || !item.due) return; publishAssignment(item); setItem({ title: '', instructions: '', audience: 'SH2 Class Group', due: '' }); setNotice('Assignment has been delivered to the selected class group.'); };
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Assignment publishing</h1><p className="page-header__subtitle">Send coursework directly to a class representative or the full class group. Students receive published work in their portal.</p></div><div className="workflow-grid"><section className="panel"><div className="panel__header"><h2 className="panel__title">Published assignments</h2></div><div className="workflow-list">{assignments.map((a) => <article key={a.id}><strong>{a.title}</strong><span>{a.audience} · Due {date(a.due)}</span><p>{a.instructions}</p><small>Published by {a.author}</small></article>)}</div></section><form className="panel workflow-form" onSubmit={submit}><div className="panel__header"><h2 className="panel__title"><ClipboardList size={16}/> Send assignment</h2></div><div className="panel__body"><label>Assignment title<input required value={item.title} onChange={(e) => setItem({ ...item, title: e.target.value })}/></label><label>Send to<select value={item.audience} onChange={(e) => setItem({ ...item, audience: e.target.value })}><option>SH2 Class Group</option><option>SH2 Class Representative</option><option>Grade 10-A Class Group</option><option>Grade 10-A Class Representative</option></select></label><label>Instructions<textarea required rows="4" value={item.instructions} onChange={(e) => setItem({ ...item, instructions: e.target.value })}/></label><label>Due date<input type="date" required value={item.due} onChange={(e) => setItem({ ...item, due: e.target.value })}/></label><button className="workflow-button" type="submit"><Send size={15}/> Send to class</button>{notice && <p className="workflow-success"><CheckCircle2 size={15}/>{notice}</p>}</div></form></div></div>;
}

export function ParentProgress({ childName = 'Benjamin Edwards' }) {
  const { results, academicCalendar } = usePortalData();
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Progress & academic calendar</h1><p className="page-header__subtitle">Results and dates below are published by teaching staff. Parents can view them but cannot edit them.</p></div><div className="workflow-grid"><section className="panel"><div className="panel__header"><h2 className="panel__title">Staff-published progress · {childName}</h2><span className="status-pill status-pill--success">Verified</span></div><table className="data-table"><thead><tr><th>Subject</th><th>Score</th><th>Grade</th><th>Lecturer</th><th>Published</th></tr></thead><tbody>{results.map((r) => <tr key={r.id}><td>{r.subject}</td><td>{r.score}%</td><td><span className="status-pill status-pill--success">{r.grade}</span></td><td>{r.lecturer}</td><td>{r.updatedAt}</td></tr>)}</tbody></table></section><section className="panel"><div className="panel__header"><h2 className="panel__title">Academic calendar</h2></div><CalendarList items={academicCalendar}/></section></div></div>;
}

export function ParentFees({ childName = 'Benjamin Edwards' }) {
  const { feeAccounts, messages } = usePortalData(); const account = feeAccounts.find((item) => item.child === childName) || feeAccounts[0]; const balance = account.billed - account.paid; const reminders = messages.filter((m) => m.to === 'Parents' && (/fee|payment|balance/i.test(`${m.subject} ${m.body}`)));
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Fees & account statement</h1><p className="page-header__subtitle">This account is maintained by the school accounts team. Payment status and reminders are shown for your selected child.</p></div><div className="workflow-grid"><section className="panel"><div className="panel__header"><h2 className="panel__title">{account.child} · {account.school}</h2><span className={`status-pill ${balance ? 'status-pill--warn' : 'status-pill--success'}`}>{account.status}</span></div><div className="panel__body fee-summary"><div><span>Term billed</span><strong>GHS {account.billed.toLocaleString()}</strong></div><div><span>Payments received</span><strong>GHS {account.paid.toLocaleString()}</strong></div><div><span>Outstanding balance</span><strong className={balance ? 'fee-balance' : ''}>GHS {balance.toLocaleString()}</strong></div><p>Account source: School Accounts · {account.term}. Contact Accounts for a receipt, correction or payment plan.</p></div></section><section className="panel"><div className="panel__header"><h2 className="panel__title"><MessageSquare size={16}/> Staff fee notices</h2></div><div className="workflow-list">{reminders.length ? reminders.map((m) => <article key={m.id}><strong>{m.subject}</strong><span>{m.from} · {m.sentAt}</span><p>{m.body}</p></article>) : <p className="workflow-empty">No fee reminders have been sent.</p>}</div></section></div></div>;
}

export function StudentMessagesAssignments() {
  const { messages, assignments, sendMessage } = usePortalData(); const [body, setBody] = useState(''); const [notice, setNotice] = useState(''); const staffMessages = messages.filter((m) => m.to === 'Students' || m.recipient === 'Kwame Edwards');
  const submit = (e) => { e.preventDefault(); if (!body.trim()) return; sendMessage({ from: 'Kwame Edwards', senderRole: 'Student', to: 'Staff', recipient: 'Mr. Samuel Amponsah', subject: 'Student message', body: body.trim() }); setBody(''); setNotice('Your message has been delivered to the Staff Portal inbox.'); };
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Assignments & messages</h1><p className="page-header__subtitle">Published work from lecturers and a direct, logged connection to staff.</p></div><div className="workflow-grid"><section className="panel"><div className="panel__header"><h2 className="panel__title">My published assignments</h2></div><div className="workflow-list">{assignments.filter((a) => /SH2/.test(a.audience)).map((a) => <article key={a.id}><strong>{a.title}</strong><span>{a.audience} · Due {date(a.due)}</span><p>{a.instructions}</p><small>{a.author}</small></article>)}</div></section><section className="panel workflow-form"><div className="panel__header"><h2 className="panel__title"><MessageSquare size={16}/> Message staff</h2></div><form className="panel__body" onSubmit={submit}><label>Message to Mr. Samuel Amponsah<textarea rows="5" required value={body} onChange={(e) => setBody(e.target.value)} placeholder="Ask your lecturer or share an update…"/></label><button className="workflow-button" type="submit"><Send size={15}/> Send to staff</button>{notice && <p className="workflow-success"><CheckCircle2 size={15}/>{notice}</p>}</form><div className="workflow-list">{staffMessages.map((m) => <article key={m.id}><strong>{m.subject}</strong><span>{m.from} · {m.sentAt}</span><p>{m.body}</p></article>)}</div></section></div></div>;
}

export function PortalSettings({ portal }) {
  const { profiles, theme, updateProfile, setTheme } = usePortalData(); const profile = profiles[portal]; const [name, setName] = useState(profile.name); const [photo, setPhoto] = useState(profile.photo); const [notice, setNotice] = useState('');
  const submit = (e) => { e.preventDefault(); updateProfile(portal, { name, photo }); setNotice('Profile saved on this device.'); };
  return <div className="workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Settings</h1><p className="page-header__subtitle">Manage your profile details and preferred interface appearance.</p></div><div className="workflow-grid"><form className="panel workflow-form" onSubmit={submit}><div className="panel__header"><h2 className="panel__title"><UserRound size={16}/> Profile</h2></div><div className="panel__body"><div className="profile-preview">{photo ? <img src={photo} alt="Profile preview"/> : <span>{name.charAt(0)}</span>}</div><label>Display name<input value={name} onChange={(e) => setName(e.target.value)} required/></label><label>Profile image<input type="file" accept="image/*" onChange={(e) => { const file=e.target.files?.[0]; if (!file) return; const reader=new FileReader(); reader.onload=()=>setPhoto(reader.result); reader.readAsDataURL(file); }}/></label><button className="workflow-button" type="submit">Save profile</button>{notice && <p className="workflow-success"><CheckCircle2 size={15}/>{notice}</p>}</div></form><section className="panel"><div className="panel__header"><h2 className="panel__title"><Settings size={16}/> Appearance</h2></div><div className="panel__body theme-options"><p>Choose the display mode used across all portals on this device.</p><button onClick={() => setTheme('light')} className={theme === 'light' ? 'theme-choice active' : 'theme-choice'}>☀ Light mode</button><button onClick={() => setTheme('dark')} className={theme === 'dark' ? 'theme-choice active' : 'theme-choice'}>◐ Dark mode</button></div></section></div></div>;
}

function CalendarList({ items }) { return <div className="calendar-list">{items.map((item) => <div key={item.id}><span className="calendar-type">{item.type}</span><strong>{item.title}</strong><small>{date(item.start)}{item.end && item.end !== item.start ? ` - ${date(item.end)}` : ''}</small></div>)}</div>; }
function date(value) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : 'Date to be confirmed'; }
