import React, { useState } from 'react';
import { CheckCircle2, Download, FileUp, Send } from 'lucide-react';
import { usePortalData } from '../../data/PortalStore';
import { downloadPublishedReport } from '../../data/reportDownload';
import './ReportWorkflow.css';

const SEMESTERS = ['Semester 1 · 2026', 'Semester 2 · 2026', 'Semester 1 · 2027'];
const CHILDREN = ['Benjamin Edwards', 'Adwoa Edwards'];

export function ParentReports({ child }) {
  const { reportRequests, publishedReports, requestReport } = usePortalData();
  const [semester, setSemester] = useState(SEMESTERS[0]);
  const [note, setNote] = useState('');
  const [notice, setNotice] = useState('');
  const requests = reportRequests.filter((request) => request.child === child.name);
  const submit = (event) => { event.preventDefault(); requestReport({ child: child.name, semester, note }); setNotice(`Your ${semester} report request has been sent to the teaching team.`); setNote(''); };
  return <div className="report-workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Reports & result requests</h1><p className="page-header__subtitle">Request {child.name}'s semester result. The exact result file uploaded by the lecturer becomes available here and in the student result centre.</p></div><div className="report-grid"><form className="panel report-form" onSubmit={submit}><div className="panel__header"><h2 className="panel__title">Request a semester result</h2></div><div className="panel__body"><label>Child<input value={child.name} readOnly /></label><label>Semester<select value={semester} onChange={(event) => setSemester(event.target.value)}>{SEMESTERS.map((item) => <option key={item}>{item}</option>)}</select></label><label>Note for the lecturer (optional)<textarea value={note} onChange={(event) => setNote(event.target.value)} rows="4" placeholder="Add a short request or question…" /></label><button className="report-button" type="submit"><Send size={15}/> Request result</button>{notice && <p className="report-success"><CheckCircle2 size={15}/>{notice}</p>}</div></form><section className="panel report-instructions"><div className="panel__header"><h2 className="panel__title">How it works</h2></div><div className="panel__body"><ol><li>Choose your child and semester, then send the request.</li><li>The lecturer receives it in Staff Portal → Reports and uploads the file.</li><li>The same uploaded file appears in both parent and student result centres.</li></ol></div></section></div><section className="panel request-status"><div className="panel__header"><h2 className="panel__title">{child.name}'s requests</h2></div>{requests.length ? requests.map((request) => { const report = publishedReports.find((item) => item.id === request.id); return <div className="request-row" key={request.id}><span><strong>{request.semester}</strong><small>Requested {request.requestedAt}</small></span><span className={`status-pill ${request.status === 'Available' ? 'status-pill--success' : 'status-pill--warn'}`}>{request.status}</span>{report && <button className="report-button" onClick={() => downloadPublishedReport(report)}><Download size={14}/> Download {report.fileName}</button>}</div>; }) : <p className="report-empty">No result requests for {child.name} yet.</p>}</section></div>;
}

export function TeacherReports() {
  const { reportRequests, uploadRequestedReport } = usePortalData();
  const [notice, setNotice] = useState('');
  const upload = (request) => (event) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { uploadRequestedReport({ id: request.id, fileName: file.name, fileData: reader.result, fileType: file.type }); setNotice(`${file.name} is now available to ${request.child}'s parent and the student result centre.`); }; reader.readAsDataURL(file); event.target.value = ''; };
  return <div className="report-workflow animate-fade-up"><div className="page-header"><h1 className="page-header__title">Parent report requests</h1><p className="page-header__subtitle">Review parent requests, then upload the semester result file. Parents receive the download direction in their portal.</p></div><section className="panel request-status"><div className="panel__header"><h2 className="panel__title">Open requests</h2></div>{reportRequests.length ? reportRequests.map((request) => <div className="teacher-request-row" key={request.id}><span><strong>{request.child} · {request.semester}</strong><small>{request.note || 'No additional note'}<br/>Requested {request.requestedAt}</small></span><span className={`status-pill ${request.status === 'Available' ? 'status-pill--success' : 'status-pill--warn'}`}>{request.status}</span>{request.status === 'Requested' ? <label className="report-upload"><FileUp size={14}/> Upload result<input type="file" accept=".csv,.pdf,.xlsx" onChange={upload(request)} /></label> : <small className="upload-name">{request.fileName}<br/>Uploaded {request.uploadedAt}</small>}</div>) : <p className="report-empty">No parent result requests yet.</p>}</section>{notice && <p className="report-success report-bottom-notice"><CheckCircle2 size={15}/>{notice}</p>}<section className="panel report-instructions"><div className="panel__header"><h2 className="panel__title">Student access</h2></div><div className="panel__body"><p>Use Staff Portal → Grades to publish individual results. Students can then open Student Portal → My Grades and download their current result sheet to their local machine.</p></div></section></div>;
}
