export const SEARCH_CATALOG = [
  // --- Admin Portal ---
  {
    id: 'adm-onboard',
    title: 'Onboard New Student',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Onboard Student',
    tab: 'single',
    category: 'Admin',
    icon: 'UserPlus',
    description: 'Register a new student, assign RFID card UID, generate REMALJ student ID, credentials, and billing account.',
    keywords: ['onboard', 'new student', 'register student', 'add student', 'enroll student', 'rfid', 'admission', 'student id', 'create student', 'learner']
  },
  {
    id: 'adm-bulk-onboard',
    title: 'Bulk Student Upload (CSV / Excel)',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Onboard Student',
    tab: 'bulk',
    category: 'Admin',
    icon: 'UploadCloud',
    description: 'Upload Excel (.xlsx) or CSV spreadsheet to onboard multiple students in batch with automatic credential generation.',
    keywords: ['bulk', 'upload', 'import', 'csv', 'excel', 'batch', 'spreadsheet', 'mass onboard', 'students import']
  },
  {
    id: 'adm-roster',
    title: 'Student Roster & Learner Directory',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Student Roster',
    category: 'Admin',
    icon: 'Users',
    description: 'Browse complete school roster, filter by class/grade, edit student bio data, and export CSV roster.',
    keywords: ['roster', 'student roster', 'directory', 'all students', 'student list', 'search students', 'class list', 'export students']
  },
  {
    id: 'adm-apps',
    title: 'Admissions Applications & Enrollment',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Applications & Forms',
    category: 'Admin',
    icon: 'FileText',
    description: 'Review incoming admission applications, update interview statuses, and enroll accepted applicants into roster.',
    keywords: ['admission', 'applications', 'enroll applicant', 'admit', 'admission forms', 'new applicant', 'interview status']
  },
  {
    id: 'adm-create-app',
    title: 'Create Admission Application Form',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Applications & Forms',
    isCreatingApp: true,
    category: 'Admin',
    icon: 'PlusCircle',
    description: 'Open and fill the official RCIS learner admission application form for new incoming applicants.',
    keywords: ['new application', 'create application', 'admissions form', 'apply', 'register applicant']
  },
  {
    id: 'adm-uac',
    title: 'User Access Control (UAC) & Password Reset',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'User Access Control (UAC)',
    category: 'Admin',
    icon: 'Key',
    description: 'Manage security credentials, reset student and parent passwords, override staff login passwords.',
    keywords: ['uac', 'password', 'reset password', 'user access', 'credentials', 'security', 'login access', 'forgot password']
  },
  {
    id: 'adm-rfid-cards',
    title: 'RFID Smart Card Issuance & Reader',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Card Issuance & Smart Identity',
    category: 'Admin',
    icon: 'CreditCard',
    description: 'Link physical USB/Bluetooth RFID card codes to learners, issue parent pickup cards, check card status.',
    keywords: ['rfid', 'smart card', 'nfc', 'card reader', 'card issuance', 'pickup card', 'scan card', 'card uid']
  },
  {
    id: 'adm-attendance',
    title: 'Attendance Terminal & Parent SMS Alerts',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Attendance & SMS Control',
    category: 'Admin',
    icon: 'MessageSquare',
    description: 'Monitor daily attendance scans, dispatch instant SMS alerts to parents for absent learners, check SMS credit balance.',
    keywords: ['attendance', 'sms', 'sms alert', 'absent', 'scan attendance', 'roll call', 'sms balance', 'smsonlinegh']
  },
  {
    id: 'adm-exam-reg',
    title: 'Register for Exams & Candidate Slips',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Register for Exams',
    category: 'Admin',
    icon: 'Award',
    description: 'Enroll candidate students into BECE and terminal exams, assign exam index numbers, print candidate registration slips.',
    keywords: ['exam registration', 'bece', 'candidate slip', 'index number', 'register exams', 'exam candidates']
  },
  {
    id: 'adm-transcripts',
    title: 'Transcripts & Class Results Approval',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Transcripts & Results',
    category: 'Admin',
    icon: 'CheckCircle2',
    description: 'Pre-audit and approve teacher score sheets, inspect student terminal transcripts and GES 9-point scale results.',
    keywords: ['transcript', 'results', 'approve results', 'grades', 'score sheet approval', 'academic record', 'bece scale']
  },
  {
    id: 'adm-pre-audit-pv',
    title: 'Pre-Audit & Approve Payment Vouchers (PV)',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Pre-Audit & Approve PV',
    category: 'Admin',
    icon: 'DollarSign',
    description: 'Inspect expenditure requisitions, pre-audit payment vouchers, and grant Headmaster approval for financial disbursements.',
    keywords: ['pv', 'payment voucher', 'pre audit', 'approve pv', 'audit remarks', 'requisition', 'financial approval', 'expenses']
  },
  {
    id: 'adm-fee-schedule',
    title: 'Official School Fee Schedule & Rates',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Official Fee Schedule',
    category: 'Admin',
    icon: 'Coins',
    description: 'Define term school fees structure, compulsory bills, boarding levies, feeding rates, and tuition fees per level.',
    keywords: ['fee schedule', 'fee structure', 'tuition fees', 'school fees', 'compulsory bill', 'rates', 'bill structure']
  },
  {
    id: 'adm-academic-settings',
    title: 'Academic Settings & Term Calendar Rules',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Academic Settings',
    category: 'Admin',
    icon: 'Sliders',
    description: 'Configure active academic year, term dates, vacation date, class test vs exam weights (50/50), and GES grading system.',
    keywords: ['academic settings', 'term dates', 'vacation date', 'grading system', 'test weight', 'exam weight', '50 50', 'settings']
  },
  {
    id: 'adm-staff-directory',
    title: 'Classes & Staff Faculty Directory',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Classes & Staff',
    category: 'Admin',
    icon: 'GraduationCap',
    description: 'View teaching staff, assign class teachers, configure grade levels, departments, and phone contact details.',
    keywords: ['staff directory', 'teachers', 'class teacher', 'faculty', 'classes', 'departments', 'assign teacher']
  },
  {
    id: 'adm-security-alerts',
    title: 'Security Logs & Intrusion Alerts',
    portal: 'admin',
    portalLabel: 'Admin Portal',
    portalColor: '#4a1d6e',
    nav: 'Security & Intrusion Alerts',
    category: 'Admin',
    icon: 'ShieldAlert',
    description: 'Monitor system security events, failed login attempts, firewall threat logs, and audit trails.',
    keywords: ['security alerts', 'firewall', 'intrusion', 'audit logs', 'unauthorized access', 'security threats']
  },

  // --- Accounts / Finance Portal ---
  {
    id: 'acc-accept-payment',
    title: 'Accept Fee Payment (Receipt Entry)',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'SIMS Auth & Login Terminal',
    simsTab: 'Student Services Centre',
    category: 'Finance',
    icon: 'Receipt',
    description: 'Record student tuition and fee payments (Cash, MoMo, Bank), calculate balance, and print instant official receipt.',
    keywords: ['accept payment', 'pay fees', 'receipt entry', 'issue receipt', 'fee payment', 'cashier', 'mobile money', 'payment entry']
  },
  {
    id: 'acc-reprint-receipt',
    title: 'Reprint Fee Payment Receipt',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'SIMS Auth & Login Terminal',
    simsTab: 'Student Services Centre',
    category: 'Finance',
    icon: 'Printer',
    description: 'Search payment history by receipt number or student name and generate reprint copy of official school fee receipt.',
    keywords: ['reprint receipt', 'print receipt', 'find receipt', 'receipt lookup', 'duplicate receipt']
  },
  {
    id: 'acc-prep-bills',
    title: 'Prepare Student Academic Bills',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Fee Structure & Rates',
    category: 'Finance',
    icon: 'FileSpreadsheet',
    description: 'Create and customize next term student compulsory bills, optional requisitions, and print official student bill sheets.',
    keywords: ['prepare bill', 'student bill', 'print bill', 'compulsory bill', 'optional bill', 'requisitions', 'fee billing']
  },
  {
    id: 'acc-debtors',
    title: 'Fee Debtors & Arrears Ledger',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Fee Debtors & Arrears',
    category: 'Finance',
    icon: 'AlertTriangle',
    description: 'Inspect learners with outstanding fee balances, generate debtors report, and dispatch automated SMS payment reminders.',
    keywords: ['debtors', 'owing fees', 'arrears', 'outstanding balance', 'fee reminder', 'defaulters', 'unpaid fees']
  },
  {
    id: 'acc-daily-collections',
    title: 'Daily Cashier Collection Summary',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Daily Collection Summary',
    category: 'Finance',
    icon: 'TrendingUp',
    description: 'Audit total revenue collected today, cash in drawer, mobile money deposits, and bank lodgements breakdown.',
    keywords: ['daily collection', 'cashier summary', 'revenue collected', 'daily cash', 'bank deposit', 'collection report']
  },
  {
    id: 'acc-payment-vouchers',
    title: 'Create & Manage Payment Vouchers (PV)',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Fee Ledgers & Payments',
    category: 'Finance',
    icon: 'FileCheck',
    description: 'Create school expense payment vouchers (PV), specify supplier/payee items, unit costs, and submit for pre-audit.',
    keywords: ['payment voucher', 'pv', 'create pv', 'requisition', 'expense voucher', 'disbursement', 'vendor payment']
  },
  {
    id: 'acc-payroll',
    title: 'Staff Payroll & Employee Banking Records',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Accountant Messages & Memos',
    category: 'Finance',
    icon: 'Briefcase',
    description: 'View staff payroll records, employee banking information, SSNIT numbers, and salary disbursements.',
    keywords: ['payroll', 'salary', 'staff banking', 'employee records', 'ssnit', 'wages', 'staff salary']
  },
  {
    id: 'acc-general-ledger',
    title: 'Official General Ledger & Accounts',
    portal: 'accountant',
    portalLabel: 'Accounts Portal',
    portalColor: '#0f3a4b',
    nav: 'Payment Vouchers (PV)',
    category: 'Finance',
    icon: 'BookOpen',
    description: 'Review chart of accounts, debits and credits, journal vouchers, and double-entry accounting ledger entries.',
    keywords: ['general ledger', 'accounting', 'journal entries', 'chart of accounts', 'financial statements', 'bookkeeping']
  },

  // --- Staff / Teacher Portal ---
  {
    id: 'tea-scoresheet',
    title: 'Score Sheet & Exam Marks Entry',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Score Sheet',
    category: 'Staff',
    icon: 'PenTool',
    description: 'Enter SBA Class Test marks (50%) and Terminal Exam scores (50%) for students, calculate grades & positions, and submit to headmaster.',
    keywords: ['scoresheet', 'marks entry', 'enter marks', 'class test', 'exam scores', 'grading', 'sba', '50 50', 'results entry']
  },
  {
    id: 'tea-attendance',
    title: 'Class Roll Call & Attendance',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Attendance',
    category: 'Staff',
    icon: 'CheckSquare',
    description: 'Conduct morning and afternoon class attendance roll calls, mark present/absent/late, and notify parents.',
    keywords: ['roll call', 'class attendance', 'take attendance', 'mark register', 'present absent', 'student attendance']
  },
  {
    id: 'tea-assignments',
    title: 'Create & Assign Homework Tasks',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Assignments',
    category: 'Staff',
    icon: 'BookMarked',
    description: 'Publish homework assignments, syllabus exercise prompts, and submission deadlines for learners.',
    keywords: ['assignments', 'homework', 'create assignment', 'tasks', 'classwork', 'homework submission', 'due date']
  },
  {
    id: 'tea-timetable',
    title: 'Teacher Schedule & Class Timetable',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Timetable',
    category: 'Staff',
    icon: 'Calendar',
    description: 'Check class teaching periods, subject periods, allocated room numbers, and weekly lesson schedule.',
    keywords: ['timetable', 'schedule', 'teaching periods', 'class schedule', 'lesson timetable', 'periods']
  },
  {
    id: 'tea-messages',
    title: 'Parent & Staff Messages Hub',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Messages',
    category: 'Staff',
    icon: 'Mail',
    description: 'Send direct messages to parents, discuss learner performance, receive school administrative memos.',
    keywords: ['messages', 'parent messages', 'contact parent', 'teacher chat', 'announcements', 'memos', 'inbox']
  },
  {
    id: 'tea-transport',
    title: 'School Bus Routes & Transport Manifest',
    portal: 'teacher',
    portalLabel: 'Staff Portal',
    portalColor: '#1b4d3e',
    nav: 'Transport',
    category: 'Staff',
    icon: 'Bus',
    description: 'Inspect school bus route schedules, student passenger lists, and route driver contact details.',
    keywords: ['bus', 'transport', 'bus route', 'pickup', 'driver phone', 'school bus']
  },

  // --- Parent Portal ---
  {
    id: 'par-progress',
    title: 'Child Academic Progress & Terminal Reports',
    portal: 'parent',
    portalLabel: 'Parent Portal',
    portalColor: '#1a3668',
    nav: 'Progress',
    category: 'Parent',
    icon: 'GraduationCap',
    description: 'Review ward terminal report card, subject marks, class teacher remarks, and cumulative performance trend.',
    keywords: ['progress', 'report card', 'terminal report', 'child grades', 'academic progress', 'marks', 'remarks']
  },
  {
    id: 'par-fees',
    title: 'School Fees & Payment Breakdown',
    portal: 'parent',
    portalLabel: 'Parent Portal',
    portalColor: '#1a3668',
    nav: 'Fees',
    category: 'Parent',
    icon: 'CreditCard',
    description: 'Check outstanding school fee balance, review payment receipt history, and view term fee breakdown.',
    keywords: ['fees', 'school fees', 'fee balance', 'payment receipts', 'pay fees', 'term bill', 'fee breakdown']
  },
  {
    id: 'par-transport',
    title: 'School Bus Live Tracking & Driver Details',
    portal: 'parent',
    portalLabel: 'Parent Portal',
    portalColor: '#1a3668',
    nav: 'Transport',
    category: 'Parent',
    icon: 'Navigation',
    description: 'Track school bus arrival status, check route number, and call designated bus driver directly.',
    keywords: ['bus tracking', 'school bus', 'driver contact', 'pickup time', 'dropoff', 'transport tracker']
  },
  {
    id: 'par-messages',
    title: 'Messages & Teacher Contact',
    portal: 'parent',
    portalLabel: 'Parent Portal',
    portalColor: '#1a3668',
    nav: 'Messages',
    category: 'Parent',
    icon: 'MessageCircle',
    description: 'Contact class teachers directly, submit inquiry notes, and receive school event broadcasts.',
    keywords: ['messages', 'contact teacher', 'teacher notes', 'parent inbox', 'school announcements']
  },
  {
    id: 'par-calendar',
    title: 'Academic Term Calendar & School Events',
    portal: 'parent',
    portalLabel: 'Parent Portal',
    portalColor: '#1a3668',
    nav: 'Calendar',
    category: 'Parent',
    icon: 'CalendarDays',
    description: 'Check term resumption date, midterm break, vacation date, exam weeks, and parent visiting days.',
    keywords: ['calendar', 'term dates', 'resumption date', 'vacation date', 'school events', 'holidays', 'midterm']
  },

  // --- Student Portal ---
  {
    id: 'stu-results',
    title: 'My Academic Results & Exam Scores',
    portal: 'student',
    portalLabel: 'Student Portal',
    portalColor: '#5e2d0e',
    nav: 'My Results',
    category: 'Student',
    icon: 'Award',
    description: 'View published terminal examination grades, subject scores, class positions, and teacher remarks.',
    keywords: ['my results', 'grades', 'exam scores', 'report card', 'marks', 'academic performance', 'student grades']
  },
  {
    id: 'stu-assignments',
    title: 'My Homework & Assignments',
    portal: 'student',
    portalLabel: 'Student Portal',
    portalColor: '#5e2d0e',
    nav: 'Assignments',
    category: 'Student',
    icon: 'BookOpenCheck',
    description: 'Check pending homework tasks, study materials, project guidelines, and submission deadlines.',
    keywords: ['homework', 'assignments', 'my tasks', 'classwork', 'due dates', 'pending homework']
  },
  {
    id: 'stu-timetable',
    title: 'My Class Schedule & Timetable',
    portal: 'student',
    portalLabel: 'Student Portal',
    portalColor: '#5e2d0e',
    nav: 'Timetable',
    category: 'Student',
    icon: 'Clock',
    description: 'View daily period timetable, subject schedule, teachers, and classroom room allocations.',
    keywords: ['my timetable', 'class schedule', 'periods', 'subjects schedule', 'daily classes']
  },
  {
    id: 'stu-exam-reg',
    title: 'Exam Registration & Index Slip',
    portal: 'student',
    portalLabel: 'Student Portal',
    portalColor: '#5e2d0e',
    nav: 'Exam Registration',
    category: 'Student',
    icon: 'FileText',
    description: 'Verify your exam candidate registration status, examination subjects, and official candidate index number.',
    keywords: ['exam registration', 'index number', 'bece candidate', 'candidate slip', 'registered exams']
  },
  {
    id: 'stu-bus',
    title: 'My Assigned Bus Route',
    portal: 'student',
    portalLabel: 'Student Portal',
    portalColor: '#5e2d0e',
    nav: 'My Bus',
    category: 'Student',
    icon: 'Bus',
    description: 'View assigned school bus route number, designated pickup stop, and driver contact number.',
    keywords: ['my bus', 'bus route', 'pickup stop', 'school bus', 'driver phone']
  }
];
